name: 0_o

on:
  schedule:
    - cron: '*/10 * * * *'  
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GH_USER: ${{ secrets.GH_USER }}
      MAIN_REPO: ${{ secrets.MAIN_REPO }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Update
      run: |
        sudo apt-get update && sudo apt-get install -y wget p7zip-full
        wget -N --no-if-modified-since https://raw.githubusercontent.com/sevcator/zapret-ps1/main/zapret.ps1
        wget -N --no-if-modified-since https://raw.githubusercontent.com/sevcator/dnscrypt-ps1/main/dnscrypt.ps1
        wget -N --no-if-modified-since https://github.com/sevcator/zapret-magisk/releases/latest/download/zapret-Magisk.zip
        wget -N --no-if-modified-since https://raw.githubusercontent.com/sevcator/zapret-magisk/main/update.json
        wget -N --no-if-modified-since https://raw.githubusercontent.com/sevcator/zapret-magisk/main/CHANGELOG.md
        
        7z x zapret-Magisk.zip -oextracted_module
        rm zapret-Magisk.zip
        
        sed -i "s|updateJson=https://raw.githubusercontent.com/[^ ]*|updateJson=https://raw.githubusercontent.com/${GH_USER}/${MAIN_REPO}/main/update.json|g" extracted_module/module.prop
        7z a zapret-Magisk.zip ./extracted_module/*
        rm -rf extracted_module
        
        sed -i "s|https://github.com/sevcator/zapret-ps1/raw/refs/heads/main/files|https://github.com/${GH_USER}/zapret-ps1/raw/refs/heads/main/files|g" zapret.ps1
        sed -i "s|https://github.com/sevcator/dnscrypt-ps1/raw/refs/heads/main/files|https://github.com/${GH_USER}/${MAIN_REPO}/raw/refs/heads/main/files|g" dnscrypt.ps1
        sed -i "s|https://github.com/sevcator/zapret-magisk/releases/download/.*\.zip|https://raw.githubusercontent.com/${GH_USER}/${MAIN_REPO}/main/zapret-Magisk.zip|g" update.json
        sed -i "s|https://raw.githubusercontent.com/sevcator/zapret-magisk/.*\.md|https://raw.githubusercontent.com/${GH_USER}/${MAIN_REPO}/main/CHANGELOG.md|g" update.json
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        current_date=$(date '+%Y-%m-%d %H:%M:%S')
        git commit -m "⚡ Updated at $current_date" || echo "No changes to commit"
        git push origin main
